version: '3.1'

services:

  web:
    container_name: gin-erp-api
    build:
      context: .
      dockerfile: gin-erp-app.Dockerfile
    ports:
      - 8080:8080
    environment:
      GIN_MODE: release
    networks: 
      - gin-erp-network
    depends_on:
      - db
    links:
      - db

  db:
    container_name: gin-erp-db
    restart: always
    networks:
      - gin-erp-network
    build:
      context: .
      dockerfile: gin-erp-db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: library
      MYSQL_USER: developer
      MYSQL_PASSWORD: 123
    ports:
      - 3307:3306
    volumes:
      - "db-data:/var/lib/mysql"

volumes:
  db-data:

networks:
  gin-erp-network: